#!/bin/bash

while [[ $choice -ne 8 ]]
echo -e " \n1. Operating System information\n"
echo -e "\n2. Hostaname inforamtion\n"
echo -e "\n3. Memory details\n"
echo -e "\n4. My disk usage\n"
echo -e "\n5. Network Ip details\n"
echo -e "\n6. Last logged users\n"
echo -e "\n7. Process usage\n"
echo -e "\n8. Exit\n"

echo "Enter your choice"
read choice

do
        case $choice in
                1)
                        echo "Your linux system information : $(uname -a)"
                ;;
                2)
                        echo "Hostname is : $(hostname)"
                ;;
                3)
                        echo "$(free -g)"
                ;;
                4)
                        echo "$(df -h)"
                ;;
                5)
                        echo "Network Ip detalis : $(ip a)"

                ;;
                6)
                        echo "Last logged user : $(last)"
                ;;
                7)
                        echo "Process usage : "
                        top
                ;;
                8)
                        echo "Bye Bye"
                        exit 1
                ;;
        esac
done
